name: emergency-services-locator
region: lon

# Database component (PostgreSQL with PostGIS)
databases:
  - name: emergency-db
    engine: PG
    version: "15"
    production: false
    db_name: emergency_db
    db_user: emergency_user

# Web service component
services:
  - name: emergency-django
    github:
      repo: Riovo/Emergency-Services-Locator
      branch: main
      deploy_on_push: true
    
    dockerfile_path: ./backend/Dockerfile.prod
    
    http_port: 8000
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    envs:
      - key: DATABASE_NAME
        scope: RUN_TIME
        value: ${emergency-db.DATABASE_NAME}
      - key: DATABASE_USER
        scope: RUN_TIME
        value: ${emergency-db.DATABASE_USERNAME}
      - key: DATABASE_PASSWORD
        scope: RUN_TIME
        value: ${emergency-db.DATABASE_PASSWORD}
      - key: DATABASE_HOST
        scope: RUN_TIME
        value: ${emergency-db.DATABASE_HOST}
      - key: DATABASE_PORT
        scope: RUN_TIME
        value: ${emergency-db.DATABASE_PORT}
      - key: DJANGO_SECRET_KEY
        scope: RUN_TIME
        value: ${DJANGO_SECRET_KEY}
      - key: DEBUG
        scope: RUN_TIME
        value: "False"
      - key: OPENCAGE_API_KEY
        scope: RUN_TIME
        value: ${OPENCAGE_API_KEY}
      - key: ALLOWED_HOSTS
        scope: RUN_TIME
        value: ${_APP_DOMAIN}
    
    health_check:
      http_path: /
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

