# Generated by Django 4.2.7

from django.db import migrations, models
import django.contrib.gis.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('hospital', 'Hospital'), ('police', 'Police Station'), ('fire', 'Fire Station')], max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('capacity', models.IntegerField(default=0, help_text='Bed capacity for hospitals')),
                ('is_24_hours', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='emergencyservice',
            index=models.Index(fields=['service_type'], name='services_em_service_4e1bf5_idx'),
        ),
    ]